#!/bin/bash
type docker-compose >/dev/null 2>&1 || { echo >&2 "I require docker-compose but it's not installed.  Aborting."; exit 1; }

#get subdir
DIR=$(pwd)
SUBDIR=$(basename $DIR)
VIRTUAL_HOST=$SUBDIR
echo "SubDir:$SUBDIR"

# set TLD with dot ie: .lab
DOCKER_TLD=".lab"

echo "DOCKER_TLD:$DOCKER_TLD"

# check if subnet alrady crated
subnet=1
netfamily='172.18'

# check if the subnet already exists
networkname=$SUBDIR"_default"
echo "networkname: $networkname"
s=$(docker network inspect $networkname | grep Subnet | grep $netfamily )

# find a suitable subnet for this environment
if [ -z "${s##*Error*}" ]; then
    echo "network: $networkname does not exists..."
    while :
    net="$netfamily.$subnet.0"
        do
    	FREE=`ip addr |grep $netfamily.$subnet`
        echo "Probing Net: $net...."
    	
    	if [ ${#FREE} = 0 ]; then
    	    echo "Network: $net is free!";
    	    break;
    	else
    	echo "network $net is busy";
    	((subnet++));
    	fi
    done
else
    subnet=${s:38:1}
    net="$netfamily.$subnet.0"
    echo "Network: $net already created!";
    
    
fi
echo "Network: $net already created!";


#exit;
#export as enviroment variables
export DOCKER_TLD
export SUBNETWORK="$netfamily.$subnet"
export NETWORK=$net
export VIRTUAL_HOST=$VIRTUAL_HOST

echo "================================================"
echo "STARTING:: $VIRTUAL_HOST.lab environment"
echo "NETWORK=$NETWORK"
echo "SUBNETWORK=$SUBNETWORK"
echo "================================================"

case "$1" in
    start)
            echo “Starting stack: daemon”
            docker-compose up -d
            echo “.”
            # now get the adapter
            addr=$(ip addr |grep $netfamily.$subnet)
            adapter=${addr:36:16};
            echo "Interface name: $adapter"
            
            echo "echo IPTABLES"
            #add propper IPTABLE rule
            ipt_cmd="iptables -D DOCKER -d $net/24 ! -i $adapter -o $adapter -j ACCEPT"
            echo $ipt_cmd
            eval $ipt_cmd
            
            ipt_cmd="iptables -I DOCKER -d $net/24 ! -i $adapter -o $adapter -j ACCEPT"
            echo $ipt_cmd
            eval $ipt_cmd
            echo "ROMOVE ISOLATION"
            echo "iptables -S DOCKER-ISOLATION | grep $adapter"
                 iptables -S DOCKER-ISOLATION | grep $adapter | while read rule ;
                do
                
                ipt_rm="iptables ${rule/A/D}"
                echo $ipt_rm
                eval $ipt_rm
                done
            ;;
    interactive)
            echo “Starting stack: interactive”
            export VIRTUAL_HOST=$2
            docker-compose up
            echo “.”
            ;;
    stop) 
          echo –n “Stopping stack: stack”
            docker-compose stop $2
           ;;
    pull) 
        echo –n “Pulling new images”
            docker-compose pull
          echo –n “Removing stack: stack”
            docker rm stack
          echo “.”
          ;;
   restart)
          echo –n “Restarting stack:”
            echo “.”
                docker-compose restart $2
            ;;
    status)
          echo –n “STATUS”
          echo “.”
              docker-compose ps
         ;;
   remove)
          echo –n “Removing stack:”
            echo “.”
            ipt_cmd="iptables -D DOCKER -d $net/24 ! -i $adapter -o $adapter -j ACCEPT"
            echo $ipt_cmd
            eval $ipt_cmd
                docker-compose stop $2
                docker-compose down $2
            ;;
        *)
          echo "Usage: /etc/init.d/stack start|stop|restart|pull|status|remove"
          exit 1
          ;;
    esac